// Copyright 2026 Satoshi Ebisawa
// SPDX-License-Identifier: Apache-2.0

//! Unit tests module
//!
//! This module contains unit tests for v3 components organized as submodules.
//!
//! Each test file in tests/unit/ must be explicitly declared as a submodule below.
//! Modules are listed in alphabetical order for maintainability.

// Test utilities (must be declared before other modules to be available)
#[path = "../tests/test_utils.rs"]
pub mod test_utils;

// Key generation helpers (re-exported from test_utils to avoid duplicate module)
pub use test_utils::keygen_helpers;

// CLI test helpers (for constants used in unit tests)
#[path = "../tests/cli/common.rs"]
pub mod cli_common;

#[path = "unit/app_context_env_dispatch_test.rs"]
pub mod app_context_env_dispatch_test;
#[path = "unit/app_identity_test.rs"]
pub mod app_identity_test;
#[path = "unit/app_key_github_test.rs"]
pub mod app_key_github_test;
#[path = "unit/app_registration_test.rs"]
pub mod app_registration_test;
#[path = "unit/cli_identity_prompt_test.rs"]
pub mod cli_identity_prompt_test;
#[path = "unit/config_resolution_ssh_signer_test.rs"]
pub mod config_resolution_ssh_signer_test;
#[path = "unit/config_resolution_test.rs"]
pub mod config_resolution_test;
#[path = "unit/config_types_test.rs"]
pub mod config_types_test;
#[path = "unit/crypto_sign_ed25519_test.rs"]
pub mod crypto_sign_ed25519_test;
#[path = "unit/crypto_test.rs"]
pub mod crypto_test;
#[path = "unit/crypto_xchacha20_poly1305_test.rs"]
pub mod crypto_xchacha20_poly1305_test;
#[path = "unit/feature_config_test.rs"]
pub mod feature_config_test;
#[path = "unit/feature_context_crypto_test.rs"]
pub mod feature_context_crypto_test;
#[path = "unit/feature_context_crypto_validation_test.rs"]
pub mod feature_context_crypto_validation_test;
#[path = "unit/feature_context_env_key_integration_test.rs"]
pub mod feature_context_env_key_integration_test;
#[path = "unit/feature_context_env_key_test.rs"]
pub mod feature_context_env_key_test;
#[path = "unit/feature_context_ssh_match_test.rs"]
pub mod feature_context_ssh_match_test;
#[path = "unit/feature_context_ssh_test.rs"]
pub mod feature_context_ssh_test;
#[path = "unit/feature_decrypt_test.rs"]
pub mod feature_decrypt_test;
#[path = "unit/feature_decrypt_unwrap_test.rs"]
pub mod feature_decrypt_unwrap_test;
#[path = "unit/feature_decrypt_unwrap_validation_test.rs"]
pub mod feature_decrypt_unwrap_validation_test;
#[path = "unit/feature_encrypt_kv_cek_test.rs"]
pub mod feature_encrypt_kv_cek_test;
#[path = "unit/feature_encrypt_kv_entry_test.rs"]
pub mod feature_encrypt_kv_entry_test;
#[path = "unit/feature_encrypt_test.rs"]
pub mod feature_encrypt_test;
#[path = "unit/feature_encrypt_wrap_test.rs"]
pub mod feature_encrypt_wrap_test;
#[path = "unit/feature_init_test.rs"]
pub mod feature_init_test;
#[path = "unit/feature_inspect_test.rs"]
pub mod feature_inspect_test;
#[path = "unit/feature_inspect_verification_test.rs"]
pub mod feature_inspect_verification_test;
#[path = "unit/feature_key_generate_test.rs"]
pub mod feature_key_generate_test;
#[path = "unit/feature_key_manage_test.rs"]
pub mod feature_key_manage_test;
#[path = "unit/feature_key_portable_export_test.rs"]
pub mod feature_key_portable_export_test;
#[path = "unit/feature_key_protection_password_encryption_test.rs"]
pub mod feature_key_protection_password_encryption_test;
#[path = "unit/feature_key_protection_password_key_derivation_test.rs"]
pub mod feature_key_protection_password_key_derivation_test;
#[path = "unit/feature_kv_disclosed_test.rs"]
pub mod feature_kv_disclosed_test;
#[path = "unit/feature_kv_test.rs"]
pub mod feature_kv_test;
#[path = "unit/feature_member_add_test.rs"]
pub mod feature_member_add_test;
#[path = "unit/feature_member_test.rs"]
pub mod feature_member_test;
#[path = "unit/feature_rewrap_common_test.rs"]
pub mod feature_rewrap_common_test;
#[path = "unit/feature_rewrap_file_op_test.rs"]
pub mod feature_rewrap_file_op_test;
#[path = "unit/feature_rewrap_file_test.rs"]
pub mod feature_rewrap_file_test;
#[path = "unit/feature_rewrap_kv_test.rs"]
pub mod feature_rewrap_kv_test;
#[path = "unit/feature_rewrap_test.rs"]
pub mod feature_rewrap_test;
#[path = "unit/feature_run_test.rs"]
pub mod feature_run_test;
#[path = "unit/feature_verify_key_loader_test.rs"]
pub mod feature_verify_key_loader_test;
#[path = "unit/feature_verify_public_key_attestation_test.rs"]
pub mod feature_verify_public_key_attestation_test;
#[path = "unit/format_context_test.rs"]
pub mod format_context_test;
#[path = "unit/format_detection_test.rs"]
pub mod format_detection_test;
#[path = "unit/format_dotenv_test.rs"]
pub mod format_dotenv_test;
#[path = "unit/format_file_enc_test.rs"]
pub mod format_file_enc_test;
#[path = "unit/format_kv_canonical_test.rs"]
pub mod format_kv_canonical_test;
#[path = "unit/format_kv_enc_debug_test.rs"]
pub mod format_kv_enc_debug_test;
#[path = "unit/format_kv_enc_ops_test.rs"]
pub mod format_kv_enc_ops_test;
#[path = "unit/format_kv_enc_structure_test.rs"]
pub mod format_kv_enc_structure_test;
#[path = "unit/format_kv_enc_test.rs"]
pub mod format_kv_enc_test;
#[path = "unit/format_schema_document_test.rs"]
pub mod format_schema_document_test;
#[path = "unit/format_signature_test.rs"]
pub mod format_signature_test;
#[path = "unit/format_token_encode_test.rs"]
pub mod format_token_encode_test;
#[path = "unit/io_config_bootstrap_test.rs"]
pub mod io_config_bootstrap_test;
#[path = "unit/io_config_store_test.rs"]
pub mod io_config_store_test;
#[path = "unit/io_keystore_member_test.rs"]
pub mod io_keystore_member_test;
#[path = "unit/io_keystore_public_key_source_test.rs"]
pub mod io_keystore_public_key_source_test;
#[path = "unit/io_keystore_resolver_test.rs"]
pub mod io_keystore_resolver_test;
#[path = "unit/io_keystore_storage_permission_test.rs"]
pub mod io_keystore_storage_permission_test;
#[path = "unit/io_keystore_test.rs"]
pub mod io_keystore_test;
#[path = "unit/io_ssh_backend_test.rs"]
pub mod io_ssh_backend_test;
#[path = "unit/io_ssh_protocol_wire_test.rs"]
pub mod io_ssh_protocol_wire_test;
#[path = "unit/io_verify_online_github_preflight_test.rs"]
pub mod io_verify_online_github_preflight_test;
#[path = "unit/io_workspace_setup_test.rs"]
pub mod io_workspace_setup_test;
#[path = "unit/jcs_test.rs"]
pub mod jcs_test;
#[path = "unit/keystore_active_test.rs"]
pub mod keystore_active_test;
#[path = "unit/keystore_helpers_test.rs"]
pub mod keystore_helpers_test;
#[path = "unit/keystore_paths_test.rs"]
pub mod keystore_paths_test;
#[path = "unit/keystore_public_keys_test.rs"]
pub mod keystore_public_keys_test;
#[path = "unit/keystore_storage_test.rs"]
pub mod keystore_storage_test;
#[path = "unit/keystore_test.rs"]
pub mod keystore_test;
#[path = "unit/model_file_enc_test.rs"]
pub mod model_file_enc_test;
#[path = "unit/model_private_key_algorithm_test.rs"]
pub mod model_private_key_algorithm_test;
#[path = "unit/model_private_key_test.rs"]
pub mod model_private_key_test;
#[path = "unit/model_public_key_test.rs"]
pub mod model_public_key_test;
#[path = "unit/model_signature_test.rs"]
pub mod model_signature_test;
#[path = "unit/model_verified_test.rs"]
pub mod model_verified_test;
#[path = "unit/schema_validator_test.rs"]
pub mod schema_validator_test;
#[path = "unit/ssh_agent_socket_test.rs"]
pub mod ssh_agent_socket_test;
#[path = "unit/ssh_agent_validation_test.rs"]
pub mod ssh_agent_validation_test;
#[path = "unit/ssh_external_pubkey_test.rs"]
pub mod ssh_external_pubkey_test;
#[path = "unit/ssh_fingerprint_test.rs"]
pub mod ssh_fingerprint_test;
#[path = "unit/ssh_helpers_test.rs"]
pub mod ssh_helpers_test;
#[path = "unit/ssh_openssh_config_integration_test.rs"]
pub mod ssh_openssh_config_integration_test;
#[path = "unit/ssh_openssh_config_test.rs"]
pub mod ssh_openssh_config_test;
#[path = "unit/ssh_parse_test.rs"]
pub mod ssh_parse_test;
#[path = "unit/ssh_protection_test.rs"]
pub mod ssh_protection_test;
#[path = "unit/ssh_protocol_key_descriptor_test.rs"]
pub mod ssh_protocol_key_descriptor_test;
#[path = "unit/ssh_protocol_types_test.rs"]
pub mod ssh_protocol_types_test;
#[path = "unit/ssh_test.rs"]
pub mod ssh_test;
#[path = "unit/ssh_verify_test.rs"]
pub mod ssh_verify_test;
#[path = "unit/sshsig_format_test.rs"]
pub mod sshsig_format_test;
#[path = "unit/support_base64url_test.rs"]
pub mod support_base64url_test;
#[path = "unit/support_fs_atomic_test.rs"]
pub mod support_fs_atomic_test;
#[path = "unit/support_fs_lock_test.rs"]
pub mod support_fs_lock_test;
#[path = "unit/support_fs_test.rs"]
pub mod support_fs_test;
#[path = "unit/support_time_test.rs"]
pub mod support_time_test;
#[path = "unit/support_validation_test.rs"]
pub mod support_validation_test;
#[path = "unit/test_utils_ed25519_backend_test.rs"]
pub mod test_utils_ed25519_backend_test;
#[path = "unit/verify_github_test.rs"]
pub mod verify_github_test;
#[path = "unit/workspace_detection_test.rs"]
pub mod workspace_detection_test;
#[path = "unit/workspace_members_test.rs"]
pub mod workspace_members_test;
